language: python

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-unidecode

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0"
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="mrp_bom_state"
  - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="mrp_bom_state"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/odoomrp/odoomrp-utils ${HOME}/odoomrp-utils
  - git clone https://github.com/OCA/banking ${HOME}/banking -b ${VERSION}
  - git clone https://github.com/OCA/purchase-workflow ${HOME}/purchase-workflow -b ${VERSION}
  - git clone https://github.com/OCA/product-attribute ${HOME}/product-attribute -b ${VERSION}
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
